### ISSUE TITLE
Question. Don't start HDD after suspend and sleep HDD on standby

### ISSUE THREAD

**Issue by voronind** [adelolmo/hd-idle#100]
I suspend PC instead of shutting down. Every time TOSHIBA DT01ACA300 HDD start working after PC wake up.
I want HDD start working by demand __only__ and sleep(not spin down) after X minutes of standby.
1. How to make don't start HDD after suspend?
2. How to make sleep HDD after standby?

Can your util to help with this?

**Comment by adelolmo** [comment]
> How to make don't start HDD after suspend?

The OS is responsible of the disk spin up.

> How to make sleep HDD after standby?

hd-idle provides only spin down (standby), not disk sleep.

> Can your util to help with this?

I'm afraid not.
