### ISSUE TITLE
Logfile won't be generate data。

### ISSUE THREAD

**Issue by Yxini** [adelolmo/hd-idle#109]
hi！
I modified the "/etc/default/hd idle" file.
`nano /etc/default/hd-idle`
The following content has been modified:
`START_HD_IDLE=true`
`HD_IDLE_OPTS="-i 0 -c ata -a /dev/disk/by-id/ata-TOSHIBA_DT01ACA100_55746MGRS -i 300 -l /var/log/hd-idle.log"`
Then, I restarted the service.
`systemctl restart hd-idle.service`
and then i waited for five minutes and saw that the hard drive was sleeping normally. But it was found that there was no data in the log file.

![1701160265971](https://github.com/adelolmo/hd-idle/assets/47093205/061e3086-0ec6-4928-80f0-4fb54b2ab397)

![图片](https://github.com/adelolmo/hd-idle/assets/47093205/5e533689-af10-4f45-bf73-79b956083f27)

**Comment by Yxini** [comment]
oh，thankyou。
The next day, I saw that the file had generated data.
It seems that I misunderstood the way the file was generated.

**Comment by Yxini** [comment]
I have another question, which is that I have a device that uses USB to convert to Sata. Due to this particularity, I want the hard drive to not be completely dormant and reduce the speed (similar to Seagate's idle_c). May I ask if there is a way to do it.

**Comment by adelolmo** [comment]
Speed reduction is not supported.

**Comment by Yxini** [comment]
Okay, thank you for your reply！
