### ISSUE TITLE
Deprecated Key?

### ISSUE THREAD

**Issue by corzocone** [adelolmo/hd-idle#115]
I recently upgraded openmediavault 6 -> 7. This is a move from Debian Buster to Debian Bookworm. I'm getting the following warning. Any idea on how I can fix this?

W: http://adelolmo.github.io/bullseye/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

**Comment by adelolmo** [comment]
Just go to https://adelolmo.github.io/#setup-repository and follow the steps.

**Comment by corzocone** [comment]
Thank you
