### ISSUE TITLE
Raspberry Pi 4B - how to build HD-Idle

### ISSUE THREAD

**Issue by hydra3333** [adelolmo/hd-idle#23]
Hello, newbie here.

I see you have mentioned in the readme that it can be build for debian.
However, I'm unsure how to build it on/for the Raspberry Pi 4B.
The readme seems to assume that Go is already installed, but I'm unfamiliar with Go and am unsure if the new Pi 32-bit OS is "armhf".

Any hints or assistance would be appreciated.

**Comment by V33m** [comment]
You don't have to build it as adelolmo already has done that. Simply download the .deb file and install it. Give the armhf version a try 👍
