### ISSUE TITLE
getting error during building

### ISSUE THREAD

**Issue by mirek190** [adelolmo/hd-idle#40]
```
github.com/adelolmo/hd-idle/io
encoding/hex
github.com/benmcclelland/sgio
github.com/adelolmo/hd-idle/sgio
github.com/adelolmo/hd-idle
##
# From git-lfs/git-lfs repo:
# dh_golang doesn't do anything here in deb 8, and it's needed in both
##
if [ "arm-linux-gnueabihf" != "x86_64-linux-gnu" ]; then\
        cp -rf obj-arm-linux-gnueabihf/bin/*/* obj-arm-linux-gnueabihf/bin/; \
fi
make[1]: Leaving directory '/home/mirek190/hd-idle'
   dh_auto_test -O--buildsystem=golang
        go test -v -p 1 github.com/adelolmo/hd-idle github.com/adelolmo/hd-idle/diskstats github.com/adelolmo/hd-idle/io github.com/adelolmo/hd-idle/sgio
?       github.com/adelolmo/hd-idle     [no test files]
fork/exec /tmp/go-build466280710/b045/diskstats.test: exec format error
FAIL    github.com/adelolmo/hd-idle/diskstats   0.155s
fork/exec /tmp/go-build466280710/b062/io.test: exec format error
FAIL    github.com/adelolmo/hd-idle/io  0.002s
?       github.com/adelolmo/hd-idle/sgio        [no test files]
FAIL
dh_auto_test: go test -v -p 1 github.com/adelolmo/hd-idle github.com/adelolmo/hd-idle/diskstats github.com/adelolmo/hd-idle/io github.com/adelolmo/hd-idle/sgio returned exit code 1
debian/rules:43: recipe for target 'build' failed
make: *** [build] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

I also tried install from the deb package under my debian ...but also got error.

sudo dpkg -i hd-idle_1.12_amd64.deb
dpkg-deb: error: 'hd-idle_1.12_amd64.deb' is not a debian format archive
dpkg: error processing archive hd-idle_1.12_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 hd-idle_1.12_amd64.deb

**Comment by adelolmo** [comment]
Are you following[ this steps](https://github.com/adelolmo/hd-idle#build-from-source) to build?

**Comment by mirek190** [comment]
Yes I flowed steps.
Even used go 1.15+

by this command

dpkg-buildpackage -a armhf -us -uc -b

**Comment by adelolmo** [comment]
Hi @mirek190 

In the first comment I see that you build for the architecture `amd64`, but in the second comment you use `armhf`. Is your target architecture different than the building one? Otherwise, you can just run `dpkg-buildpackage -us -uc -b`.

**Comment by mirek190** [comment]
I only used what is in the manual ! 
Copy - paste ... did not noticed there is for arm ... lol

dpkg-buildpackage -a armhf -us -uc -b

why there is armhf ?    ;-D
