### ISSUE TITLE
SystemV init script

### ISSUE THREAD

**Issue by esale** [adelolmo/hd-idle#41]
Hi, first of all thanks for your work.

I'd like to suggest adding a SystemV init script, like the version included in Debian repo. It would make things easier for people who likes SystemV.

If you want I can send you a copy of the script.

Regards!

**Comment by adelolmo** [comment]
Hi @esale 

I guess to refer to this one, right? 
https://salsa.debian.org/debian/hd-idle/-/blob/master/debian/hd-idle.init

**Comment by esale** [comment]
Yes, that's right!

**Comment by esale** [comment]
Great! Thanks.

**Comment by adelolmo** [comment]
@esale 
did you ever get to test if the script works?

**Comment by esale** [comment]
@adelolmo 
it still works for me.
Thanks!
