### ISSUE TITLE
Hard drive doesn't spin down after certain uptime

### ISSUE THREAD

**Issue by bkev** [adelolmo/hd-idle#45]
I am running hd-idle on a Pi v4 and it works really well. What I have noticed though is that if my pi hasn't been rebooted for a while (3 weeks for example) the hard drive doesn't spin down anymore. If I restart the hd-idle service it works for a short period again but then doesn't spin down again. 
Are there any logs I can look at to see why this is happening and if it is hd-idle? I appreciate it could be something else causing it too. 
Thanks.

**Comment by adelolmo** [comment]
Hi @bkev 
You can start by checking [the logs documentation](https://github.com/adelolmo/hd-idle#understand-the-logs).

**Comment by bkev** [comment]
Cheers I'll keep an eye on it. There aren't as many entries when it stops working but I'll see what happens now as I've just upgraded to the latest version and rebooted.
