### ISSUE TITLE
Scripting feature within hd-idle

### ISSUE THREAD

**Issue by wmd1942** [adelolmo/hd-idle#49]
I have a usbrelay module to control the cooling fan through a simple script command. Is there any way to provide the scripting capability so the scripts could be invoked when disk spin down/up?

**Comment by adelolmo** [comment]
Short answer: no.
Long answer: You could figure a way to pull /var/log/syslog for `sdx spindown` entries.

**Comment by wmd1942** [comment]
I wrote a bash script to pull hd-idle entry from syslog every minute. It works well. Thanks for the suggestion.
