### ISSUE TITLE
Run on MacoS Big Sur

### ISSUE THREAD

**Issue by erdincsk** [adelolmo/hd-idle#52]
Hello,

Is it possible to install and run hd-idle on maos?

Thnaks.

**Comment by adelolmo** [comment]
I don't provide package for macos, although it might be possible to compile the hd-idle binary to run on it.
The main question is: does macos have the file `/proc/diskstats` ?

**Comment by erdincsk** [comment]
actually i do not have such detailed info. i'm just an end-user  and asking for possibilities for mac :) but i will make a research. thanks anayway 👍
