### ISSUE TITLE
Improve use on non-systemd init scheme

### ISSUE THREAD

**Issue by hameau** [adelolmo/hd-idle#53]
Hello,

OS : Devuan beowulf, init : SysV, headless, no X server
hd-idle: v1.15, installed using amd64.deb

`hd-idle` relies on systemd to put the process into the background and to provide system logging, which causes problems under other init schemes.

As distributed, the sysvinit script (introduced in response to #43) is not usable, because `hd-idle` does not detach itself from the init process, which stalls, halting the boot process (manual line wrap for readability):
```
[....] Starting the hd-idle daemon: hd-idlesymlinkPolicy=0, defaultIdle=0, defaultCommand=ata,\
debug=false, logFile=/var/log/hd-idle.log,\
devices={name=sdb, givenName=sdb, idle=300, commandType=ata}\
{name=sdc, givenName=sdc, idle=300, commandType=ata}\
{name=sdd, givenName=sdd, idle=300, commandType=ata}\
{name=sde, givenName=sde, idle=300, commandType=ata}
```
This is the same output as running `hd-idle` from the command line (#37).

It is possible to force `hd-idle` into the background by modifying the init script like this:
```
case "$1" in
    start)
        log_daemon_msg "Starting the hd-idle daemon" "hd-idle"

---     start-stop-daemon --start --quiet --oknodo --exec $DAEMON -- $HD_IDLE_OPTS
+++     start-stop-daemon --start --quiet --oknodo --background --exec $DAEMON -- $HD_IDLE_OPTS

        log_end_msg $?
        ;;
```
This allows the system to boot, but has two problems :

- No feedback if `hd-idle` fails to start
- No system log messages (only logs to logfile option, if set)

Would it be possible to look at these problems, please?

**Comment by adelolmo** [comment]
Closed by: https://github.com/adelolmo/hd-idle/issues/93
