### ISSUE TITLE
packaged for archlinux (AUR)

### ISSUE THREAD

**Issue by mar04** [adelolmo/hd-idle#57]
Hi,
just wanted to let you know that there is now an AUR package available https://aur.archlinux.org/packages/hd-idle-go/
Suffix '-go' is there because the original hd-idle is in the official repositories of Archlinux. If you have any comments or suggestions, let me know.

**Comment by adelolmo** [comment]
Hi,

There's not much I can say about the AUR package, I'm not familiar with it.
Let me know if you experience any issue while running it, so that I can help you with the debugging.

Thanks for your contribution :)
