### ISSUE TITLE
/dev/disk/by-id in addition or instead to /dev/sdX in the logfile.

### ISSUE THREAD

**Issue by gert99** [adelolmo/hd-idle#65]
This would make it possible to get long term statistics from the logfile, because /dev/sdX could have be changed after a reboot.

**Comment by adelolmo** [comment]
Out of curiosity, what are you trying to achieve?

**Comment by gert99** [comment]
I wrote a simple bash script that reads the entire logfile (plus the rotated ones) and outputs the following values from it for each disk:

1) How many days are recorded in the log files.

2) For each hard disk: How many spin-up operations
	Today, Yesterday, Total, Total/number of days
	
3) For each hard disk: The spin-up duration in hours
	Today, Yesterday, Total, Total/Number of days
	
I want to use this to get an overview of the individual usage of each hard drive. Unfortunately, this no longer works if the assignment of /dev/sdX to the individual devices has changed.
