### ISSUE TITLE
hd-idle killed the disk?

### ISSUE THREAD

**Issue by m33x** [adelolmo/hd-idle#68]
I used hd-idle to spin down my USB HDD on my Raspberry Pi 4. But even after restarting, and on other PCs (running macOS and Windows 10 which do not have hd-idle installed) after connecting the drive it does nothing. It never starts, it never spins up again. It gets power, the white LED is on, but nothing else. Is it dead Jim?

Disk: Western Digital Elements 4TB (WDBHDW0040BBK) USB 3.0 Micro-B
I used: hd-idle_1.16_armhf.deb

**Edit:**
`lsbusb` doesn't show the disk at all. I believe it is seriously dead. While `lsusb` _hangs_ for 30 seconds, but then does not show anything (tested on different computers, not just the Pi), macOS does show the drive in the System Information but not in the disk utility.

<img width="450" alt="Screenshot 2022-01-14 at 18 41 50" src="https://user-images.githubusercontent.com/883685/149560826-6917bbd1-b55c-4ec8-9c33-a11b435694d8.png">

**Comment by adelolmo** [comment]
> Is it dead Jim?
Given the results from your investigation, I'd say it is dead.
I won't be able to guess how or why, though.

**Comment by m33x** [comment]
Thanks. I ordered a new one (this time a different brand - Seagate). I will run `hd-idle` again tomorrow, if it doesn't survive it, I will immediately return it.

**Comment by m33x** [comment]
This is what Windows 10 reports:
![usb-win](https://user-images.githubusercontent.com/883685/149563516-89f4a4c1-79ff-49f9-96f6-47d62f8acf05.jpg)

![usb-win-2](https://user-images.githubusercontent.com/883685/149563519-0552e1ad-44f9-47dc-824b-5ff146fd8428.jpg)

**Comment by adelolmo** [comment]
Are you using a power adapter to run it? AFAIK Those external disk won't get enough power from the USB cable.

**Comment by m33x** [comment]
I'm using the original USB-A to Micro B cable that was in the box with the HDD. Never had any issues with it. I would understand issues on the Pi, but not on my PC or Mac.

**Comment by m33x** [comment]
I can report back, the new disk (Seagate Portable Drive, STGX5000400, UASP, Two year warranty, 100€) works as intended. `hd-idle` can spin down and spin up the disk. No issues what so ever. 

Given the fact that the old disk was my TimeMachine backup, I guess I have to thank you and `hd-idle` for spotting this faulty disk. Try to **avoid** Western Digital Elements 4TB (WDBHDW0040BBK) disks, they are not reliable (Sadly, the warranty expired in November 2021).
