### ISSUE TITLE
hd-idle debian package

### ISSUE THREAD

**Issue by devZer0** [adelolmo/hd-idle#73]
debian is using the older/outdated hd-idle package from sourceforge. 

as there is debian support files in this hd-idle repo, is it planned that old/outdated hd-idle in debian is getting replaced with this one?

thank you

**Comment by adelolmo** [comment]
http://hd-idle.sourceforge.net (insecure link) and this project are completely unrelated.
This means that there's no contact between me and the maintainer of the [debian package](https://salsa.debian.org/debian/hd-idle) ([Alexandre Mestiashvili](https://salsa.debian.org/mestia)).
