### ISSUE TITLE
Feature: Flag for script after spin up

### ISSUE THREAD

**Issue by schaeferpm** [adelolmo/hd-idle#96]
Hey, would it be possible to add an additional flag to specify a command or script after the disk is spun up again? 

Or is there a native workaround?

(Background: was playing around with snapshots in combination of hd-idle. Would be very interesting to take snaps after or even before spin down)

**Comment by adelolmo** [comment]
This topic popped already at some point in the past: https://github.com/adelolmo/hd-idle/issues/49

**Comment by schaeferpm** [comment]
Oh okay, but it does not solve the before spindown trigger...

Is there a specific reason not allowing scripts?

**Comment by GrayXu** [comment]
You can add your scripts before the `spindownDisk`
https://github.com/adelolmo/hd-idle/blob/3ce8768d5815967c9554ca1aa5c22f939d92f708/hdidle.go#L146-L148

**Comment by adelolmo** [comment]
Hi @schaeferpm 

What are you trying to achieve? I'd like to understand your problem before potentially start working on _a_ solution.
