### ISSUE TITLE
Nothing after hd-idle command

### ISSUE THREAD

**Issue by remirr** [adelolmo/hd-idle#99]
So it seems hd-idle sometimes works and sometimes doesn't. When I open terminal and enter 'hd-idle' I get the following and it just sits there.... 

~ $ hd-idle
symlinkPolicy=0, defaultIdle=600, defaultCommand=scsi, defaultPowerCondition=0, debug=false, logFile=, devices=

If I run the command 'hd-idle -i 1900' to try and change the shutdown time, its does the same but shows 1900. If I close the window and open it again and type 'hd-idle', I just get the line above again and it does not seems to save the commands. 

I also added -l and then the destination to the empty log file I created on the desktop and nothing is written in there either. I have gone over the documentation a number of times but doesn't seem to help. 

Thank you

**Comment by adelolmo** [comment]
Hi @remirr 

I would recommend you to [install](https://github.com/adelolmo/hd-idle#install) the debian package and [run hd-idle as a service](https://github.com/adelolmo/hd-idle#run-hd-idle) (`systemctl start hd-idle`).
The configuration would then be done in the file `/etc/default/hd-idle`.
